baseURL = 'https://medina474.github.io/'
languageCode = 'fr-fr'
title = 'Emmanuel Medina'
enableRobotsTXT = true
[params]
  author = 'Emmanuel Medina'
  description = "Cours"
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = false
    noClasses = false
    style = 'vs'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.extensions.extras]
      [markup.goldmark.extensions.extras.delete]
        enable = true
      [markup.goldmark.extensions.extras.insert]
        enable = true
      [markup.goldmark.extensions.extras.mark]
        enable = true
      [markup.goldmark.extensions.extras.subscript]
        enable = true
      [markup.goldmark.extensions.extras.superscript]
        enable = true
